#!/bin/bash
User-Agent:"Mozilla/5.0 (X11; Linux x86_64)"
curl_setopt($script, CURLOPT_URL, 'https://alcasar.laplateforme.io/status.php');
curl_setopt($script, CURLOPT_USERAGENT,'Mozilla/5.0 (X11; Linux x86_64)');
curl_setopt($script, CURLOPT_POSTFIELDS, "login=login&user_name=neiji.hadhri@laplateforme.io&user_pass=a1hzam");
